# Generated by Django 3.1.4 on 2020-12-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20201206_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('interest', models.TextField(blank=True, null=True, verbose_name='User Interest')),
                ('acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.acc', verbose_name='Account')),
            ],
        ),
    ]
