# Generated by Django 3.1.4 on 2020-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20201207_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
