# Generated by Django 3.1.4 on 2020-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_acc_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
