# Generated by Django 3.1.4 on 2020-12-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20201211_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='username',
        ),
    ]
