# Generated by Django 3.1.4 on 2020-12-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_biodata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Username'),
        ),
    ]
