# Generated by Django 3.1.4 on 2020-12-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlebasedmodel',
            unique_together=set(),
        ),
    ]
