# Generated by Django 3.1.4 on 2020-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0002_auto_20201211_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebasedmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
    ]
