# Generated by Django 3.1.4 on 2020-12-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0003_auto_20201229_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbasedmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='videobasedmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Details '),
        ),
    ]
