# Generated by Django 3.1.4 on 2020-12-25 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kuesionerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='pertanyaan 1')),
                ('pertanyaan_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='pertanyaan 2')),
                ('pertanyaan_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='pertanyaan 3')),
                ('pertanyaan_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='pertanyaan 4')),
                ('pertanyaan_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='pertanyaan 5')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID User')),
            ],
        ),
        migrations.CreateModel(
            name='appLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, verbose_name='Activity')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='Access Time')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID User')),
            ],
        ),
    ]
