# Generated by Django 3.1.4 on 2021-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuesionermodel',
            name='pertanyaan_5',
            field=models.TextField(blank=True, null=True, verbose_name='pertanyaan 5'),
        ),
    ]
