# Generated by Django 3.1.4 on 2020-12-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Learning Path')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='SubTitle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Sub Title 1')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.learningpath')),
            ],
        ),
        migrations.CreateModel(
            name='SubTitle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Sub Title 2')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('SubTitle1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.subtitle1')),
            ],
        ),
        migrations.CreateModel(
            name='SubTitle3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Sub Title 3')),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('SubTitle2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.subtitle2')),
            ],
        ),
        migrations.CreateModel(
            name='SubTitle4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Sub Title 4')),
                ('details', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('SubTitle3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.subtitle3')),
            ],
        ),
    ]
